name: LooBreak Bug
description: Template for reporting bugs
body:
  - type: dropdown
    id: version
    attributes:
      label: Version
      options:
        - v1
        - v1.1
        - v1.2
        - v1.3 quiz question and answers loading on page.
        - v1.4 all 10 questions on quiz page.
        - v1.5 API brings in data and stores in Quiz collection db.
        - v1.6 Fixed issue with second click and disabled answer buttons after selected.
        - v1.7 navbar added to all pages + basic light/dark mode
        - v1.8 user tests converted to player tests. all pass on backend
        - v1.9 added in submit button and li9nk to results page when quiz is finished
        - v1.10 fixed v1.9 issue
        - v2.0 added icebreaker component to the homepage displaying a single random icebreaker on each click
        - v2.1 added frontend and backend unit tests for quiz and fixed test for update on QuizPage.jsx
        - v2.2 added feature to show LooTips - branched off Icebraker branch with similar code.
        - v2.3 fixed issue from v2.1 and v1.5 special chars and added colours to answer buttons to show selected and correct/incorrect
        - v2.4 increased icebreaker component to display 3 random icebreakers on each click
        - v2.5 fixed ticket for footer lootips
        - v2.6 completed tests for decoding HTML entities
        - v2.7 completed results page and score saving to database
        - v2.7.1 fixed issue for not showing error message when player name already exists
        - v2.8 fixed duplicate answers bleeding into next question and added detection/retry for duplicate answers from quiz API
        - v2.9 implemented leaderboard, mini leaderboard and daily reset
        - v3.0 fixed act warnings
        - v3.1 fixed react router warning
        - v3.2 Feature to add shadcn and and skeleton to components
        - v3.3 fixed quiz reload issue
        - v3.4 reset index being set in local storage. added test id's leaderboards
        - v3.5 added flush animation to footer
        - v3.7 coverage report
        - v3.8 leaderboard styling
        - v3.9 quiz page styling, light/dark mode fixed, toggle switch implemented for theme change
        - v4.0 homepage styling with shadcn for icebreaker drawer for light / dark mode and quiz button
        - v4.1 added custom images
        - v4.3 bugs/deleting-files-fixing-accessibility

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      options:
        - "Critical"
        - "High"
        - "Medium"
        - "Low"
        - "Trivial"
  - type: dropdown
    id: suggested_priority
    attributes:
      label: Suggested Priority
      description: To aid triage and review of the issue
      options:
        - High
        - Medium
        - Low
  - type: textarea
    id: observed
    attributes:
      label: Observed Behaviour
  - type: textarea
    id: expected
    attributes:
      label: Expected Behaviour
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction Steps
      value: |
        1. 
        2. 
        3.
